language: android
jdk: oraclejdk8

env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=22
   - ANDROID_BUILD_TOOLS_VERSION=28.0.3
   - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - adb shell input keyevent 82 &
  - android-wait-for-emulator
  - ./gradlew connectedCheck
  
script:
  - ./gradlew connectedAndroidTest

